/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY generate_commands.py
*  
*  ONLY EDIT PARAMETERS AS SUGGESTED.
* date : 22-11-06 14:51:22
*/

#define SYNDESI_CONFIG_INCLUDED // Do not change this

/* ######## General configuration ######### */

/*
* HOST mode : can send commands (a computer for example)
*/
#define SYNDESI_HOST_MODE

/*
* DEVICE mode : can receive commands (like a I²C interface, SPI interface, etc...)
*/
//#define SYNDESI_DEVICE_MODE

// Both can be activated at the same time to enable HYBRID mode (not enabled yet)


/* ######## Protocols configuration ####### */

/*
* ETHERNET
*
* 0 -> custom (user implemented)
* 1 -> system
*
*/
//#define SYNDESI_ETHERNET_CONTROLLER ...



// Use system Ethernet
#define USE_SYSTEM_ETHERNET


/* ######## Callbacks configuration ######## */
/*
*  
* Disabled callback :
* //#define USE_REGISTER_READ_16_REQUEST_CALLBACK
* Enabled callback
* #define USE_REGISTER_READ_16_REQUEST_CALLBACK
*
* The user must then implement it (following the prototype in callbacks.h)
*
* Each request callback follows the format :
*   command_request_callback(request, reply);
* The reply, passed as a pointer, must be editer by the user in the callback
*
* Each reply callback follows the format :
*   command_reply_callback(reply);
* No response to the device will be made
*

*/


/*
* Request callbacks (to be used in device code)
* Only active if DEVICE_MODE is defined
*/
#define USE_DEVICE_DISCOVER_REQUEST_CALLBACK
#define USE_REGISTER_READ_16_REQUEST_CALLBACK
#define USE_REGISTER_WRITE_16_REQUEST_CALLBACK
#define USE_SPI_READ_WRITE_REQUEST_CALLBACK
#define USE_SPI_WRITE_ONLY_REQUEST_CALLBACK
#define USE_I2C_READ_REQUEST_CALLBACK
#define USE_I2C_WRITE_REQUEST_CALLBACK



/*
* Reply callbacks (to be used in host code)
* Only active if HOST_MODE is defined
*/
#define USE_ERROR_REPLY_CALLBACK
#define USE_DEVICE_DISCOVER_REPLY_CALLBACK
#define USE_REGISTER_READ_16_REPLY_CALLBACK
#define USE_REGISTER_WRITE_16_REPLY_CALLBACK
#define USE_SPI_READ_WRITE_REPLY_CALLBACK
#define USE_SPI_WRITE_ONLY_REPLY_CALLBACK
#define USE_I2C_READ_REPLY_CALLBACK
#define USE_I2C_WRITE_REPLY_CALLBACK
